import React, { useState, useEffect } from 'react';
import {
  Lightbulb,
  Sparkles,
  CheckCircle2,
  XCircle,
  TrendingDown,
  ArrowRight,
  Zap,
  Filter,
  Layers,
  Award
} from 'lucide-react';
import PageHeader from '../../components/common/PageHeader';
import StatusBadge from '../../components/common/StatusBadge';
import Button from '../../components/common/Button';
import { recommendationService } from '../../services/recommendationService';
import { useToast } from '../../context/ToastContext';
import { formatCurrency, formatKWh } from '../../utils/formatters';

const RecommendationsPage = () => {
  const [recommendations, setRecommendations] = useState([]);
  const [filter, setFilter] = useState('all'); // all, active, completed
  const [loading, setLoading] = useState(true);

  const { toastSuccess, toastInfo } = useToast();

  useEffect(() => {
    const fetchRecs = async () => {
      setLoading(true);
      try {
        const data = await recommendationService.getRecommendations();
        setRecommendations(data);
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    fetchRecs();
  }, []);

  const handleComplete = async (id) => {
    await recommendationService.updateStatus(id, 'Completed');
    setRecommendations((prev) =>
      prev.map(r => r.id === id ? { ...r, status: 'Completed' } : r)
    );
    toastSuccess('Optimization marked as applied! Projected savings recorded.');
  };

  const handleDismiss = async (id) => {
    await recommendationService.updateStatus(id, 'Dismissed');
    setRecommendations((prev) =>
      prev.map(r => r.id === id ? { ...r, status: 'Dismissed' } : r)
    );
    toastInfo('Recommendation dismissed.');
  };

  const filteredRecs = recommendations.filter(r => {
    if (filter === 'active') return r.status === 'Active';
    if (filter === 'completed') return r.status === 'Completed';
    return true;
  });

  const totalActiveSavingsINR = recommendations
    .filter(r => r.status === 'Active')
    .reduce((sum, r) => sum + r.estimatedMonthlySavingsINR, 0);

  const totalActiveSavingsKWh = recommendations
    .filter(r => r.status === 'Active')
    .reduce((sum, r) => sum + r.estimatedMonthlySavingsKWh, 0);

  return (
    <div className="space-y-8">
      <PageHeader
        category="AI ENERGY OPTIMIZATION"
        title="Energy Recommendations"
        subtitle="Actionable, prioritized recommendations generated by analyzing your digital consumption deviations and appliance load profiles."
      />

      {/* Savings Summary Banner */}
      <div className="p-6 rounded-3xl bg-forest-900 text-white shadow-xl flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="space-y-2">
          <div className="flex items-center gap-2">
            <Sparkles className="w-5 h-5 text-emerald-300" />
            <h3 className="text-lg font-bold">Total Potential Monthly Savings</h3>
          </div>
          <p className="text-xs text-emerald-100 max-w-xl leading-relaxed">
            By acting on all active high and medium priority recommendations, you can reduce waste by <strong>{formatKWh(totalActiveSavingsKWh)}</strong> per billing cycle.
          </p>
        </div>

        <div className="text-right shrink-0 bg-forest-950/70 px-6 py-4 rounded-2xl border border-emerald-700/60">
          <span className="text-[10px] uppercase font-bold text-emerald-300">Estimated Cost Reduction</span>
          <p className="text-2xl font-black text-white mt-0.5">{formatCurrency(totalActiveSavingsINR)} <span className="text-xs font-semibold text-slate-300">/ mo</span></p>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex items-center justify-between">
        <h3 className="text-base font-bold text-slate-900 dark:text-white">
          Active Recommendations ({filteredRecs.length})
        </h3>

        <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl text-xs font-semibold">
          {['all', 'active', 'completed'].map((f) => (
            <button
              key={f}
              onClick={() => setFilter(f)}
              className={`px-3 py-1 rounded-lg capitalize transition-all ${
                filter === f
                  ? 'bg-white dark:bg-slate-700 text-forest-800 dark:text-emerald-300 shadow-xs font-bold'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              {f}
            </button>
          ))}
        </div>
      </div>

      {/* Recommendations Cards Grid */}
      <div className="space-y-4">
        {filteredRecs.map((rec) => {
          const isCompleted = rec.status === 'Completed';
          const isDismissed = rec.status === 'Dismissed';

          return (
            <div
              key={rec.id}
              className={`bg-white dark:bg-slate-900 border rounded-3xl p-6 shadow-sm transition-all space-y-4 ${
                isCompleted
                  ? 'border-emerald-200/80 bg-emerald-50/20 dark:border-emerald-900/40'
                  : isDismissed
                  ? 'opacity-50 border-slate-200 dark:border-slate-800'
                  : 'border-slate-200/80 dark:border-slate-800 hover:shadow-md'
              }`}
            >
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                <div className="flex items-center gap-3">
                  <div className={`w-10 h-10 rounded-2xl flex items-center justify-center font-bold ${
                    rec.priority === 'HIGH'
                      ? 'bg-rose-50 text-rose-700 dark:bg-rose-950/60 dark:text-rose-300'
                      : 'bg-amber-50 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300'
                  }`}>
                    <Lightbulb className="w-5 h-5" />
                  </div>
                  <div>
                    <div className="flex items-center gap-2">
                      <h4 className="text-sm font-bold text-slate-900 dark:text-white">{rec.title}</h4>
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full ${
                        rec.priority === 'HIGH'
                          ? 'bg-rose-50 text-rose-700 border border-rose-200 dark:bg-rose-950 dark:text-rose-300'
                          : 'bg-amber-50 text-amber-700 border border-amber-200 dark:bg-amber-950 dark:text-amber-300'
                      }`}>
                        {rec.priority} PRIORITY
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-400 font-medium mt-0.5">{rec.category}</p>
                  </div>
                </div>

                <div className="text-left sm:text-right">
                  <span className="text-[10px] font-bold uppercase text-slate-400 block">Estimated Savings</span>
                  <span className="text-sm font-bold text-forest-800 dark:text-emerald-400">
                    {formatCurrency(rec.estimatedMonthlySavingsINR)}/mo ({formatKWh(rec.estimatedMonthlySavingsKWh)})
                  </span>
                </div>
              </div>

              {/* Reason & Suggestion Box */}
              <div className="space-y-2 text-xs">
                <div className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-800/60 text-slate-700 dark:text-slate-300 leading-relaxed space-y-1">
                  <p className="font-semibold text-slate-900 dark:text-white">Detected Pattern:</p>
                  <p className="text-slate-600 dark:text-slate-300">"{rec.reason}"</p>
                </div>

                <div className="p-3.5 rounded-2xl bg-emerald-50/70 dark:bg-emerald-950/40 border border-emerald-200/70 dark:border-emerald-800/60 text-forest-900 dark:text-emerald-200 leading-relaxed space-y-1">
                  <p className="font-bold">Recommendation:</p>
                  <p className="text-slate-700 dark:text-slate-300">{rec.recommendation}</p>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="flex items-center justify-between pt-2 border-t border-slate-100 dark:border-slate-800 text-xs">
                <div>
                  {isCompleted ? (
                    <span className="inline-flex items-center gap-1.5 font-bold text-emerald-600 dark:text-emerald-400">
                      <CheckCircle2 className="w-4 h-4" />
                      Applied to Profile
                    </span>
                  ) : isDismissed ? (
                    <span className="text-slate-400">Dismissed</span>
                  ) : (
                    <span className="text-slate-500">Action Required</span>
                  )}
                </div>

                {!isCompleted && !isDismissed && (
                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleDismiss(rec.id)}
                      className="px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 text-slate-600 dark:text-slate-400 hover:bg-slate-100 font-semibold"
                    >
                      Dismiss
                    </button>
                    <Button
                      size="sm"
                      variant="primary"
                      icon={CheckCircle2}
                      onClick={() => handleComplete(rec.id)}
                    >
                      {rec.actionLabel || "Apply Optimization"}
                    </Button>
                  </div>
                )}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default RecommendationsPage;
